-- Indian Academic Dataset Expansion
-- 50+ realistic profiles from IITs, NITs, and IIITs.

INSERT OR IGNORE INTO users (name, email, bio, academic_level, preferred_role, availability, is_admin) VALUES
('Dr. Ramesh Balakrishnan', 'ramesh.b@iitm.ac.in', 'Professor at IIT Madras, focusing on Reinforcement Learning and Robotics.', 'Faculty', 'mentor', 'limited', 0),
('Dr. Sunita Deshpande', 'sunita.d@iitb.ac.in', 'Associate Professor at IIT Bombay, expert in Cryptography and Network Security.', 'Faculty', 'mentor', 'moderate', 0),
('Dr. Amitabh Sikka', 'amitabh.s@iitd.ac.in', 'Professor at IIT Delhi, researching Natural Language Processing for Indian languages.', 'Faculty', 'mentor', 'flexible', 0),
('Dr. Kavita Rao', 'kavita.r@iitk.ac.in', 'Assistant Professor at IIT Kanpur, specializing in Computer Vision and Medical Imaging.', 'Faculty', 'mentor', 'moderate', 0),
('Dr. Sanjay Murthy', 'sanjay.m@iitkgp.ac.in', 'Professor at IIT Kharagpur, expert in VLSI Design and Embedded Systems.', 'Faculty', 'mentor', 'limited', 0),
('Dr. Ananya Iyer', 'ananya.i@nitk.ac.in', 'Associate Professor at NIT Surathkal, focusing on Cloud Computing and IoT.', 'Faculty', 'mentor', 'flexible', 0),
('Arjun Reddy', 'arjun.reddy@student.iitm.ac.in', 'B.Tech student at IIT Madras, interested in High Performance Computing and C++.', 'B.Tech 4th Year', 'backend', 'flexible', 0),
('Deepak Verma', 'deepak.v@student.iitb.ac.in', 'M.Tech student at IIT Bombay, specializing in Deep Learning and PyTorch.', 'M.Tech / Masters', 'ml', 'moderate', 0),
('Isha Gupta', 'isha.g@student.iitd.ac.in', 'PhD scholar at IIT Delhi, researching low-resource NLP.', 'PhD Scholar', 'ml', 'limited', 0),
('Karan Malhotra', 'karan.m@student.iitk.ac.in', 'B.Tech student at IIT Kanpur, focusing on Blockchain and Smart Contracts.', 'B.Tech 3rd Year', 'blockchain', 'flexible', 0),
('Meera Nair', 'meera.n@student.iitkgp.ac.in', 'M.Tech student at IIT Kharagpur, expert in Data Engineering and Spark.', 'M.Tech / Masters', 'backend', 'flexible', 0),
('Rahul Sharma', 'rahul.s@student.nitk.ac.in', 'B.Tech student at NIT Surathkal, interested in DevOps and Kubernetes.', 'B.Tech 4th Year', 'devops', 'moderate', 0),
('Siddharth Jain', 'siddharth.j@student.nitw.ac.in', 'B.Tech student at NIT Warangal, focused on Frontend with React and Next.js.', 'B.Tech 3rd Year', 'frontend', 'flexible', 0),
('Tanvi Hegde', 'tanvi.h@student.nitt.ac.in', 'B.Tech student at NIT Trichy, interested in UI/UX and Figma.', 'B.Tech 2nd Year', 'design', 'flexible', 0),
('Vikram Singh', 'vikram.s@student.iiit.ac.in', 'PhD scholar at IIIT Hyderabad, researching Computer Vision for Autonomous Vehicles.', 'PhD Scholar', 'ml', 'moderate', 0),
('Aditi Pant', 'aditi.p@student.bits.ac.in', 'B.E student at BITS Pilani, specializing in Fullstack Development with MERN.', 'B.Tech 4th Year', 'fullstack', 'flexible', 0),
('Rohan Das', 'rohan.d@student.ju.ac.in', 'M.E student at Jadavpur University, researching IoT and Edge AI.', 'M.Tech / Masters', 'ml', 'moderate', 0),
('Sneha Pillai', 'sneha.p@student.annauniv.edu', 'B.E student at Anna University, interested in Backend with Go and Microservices.', 'B.Tech 3rd Year', 'backend', 'flexible', 0),
('Manish Kumar', 'manish.k@student.vnit.ac.in', 'B.Tech student at VNIT Nagpur, focusing on Cybersecurity and Pentesting.', 'B.Tech 4th Year', 'backend', 'limited', 0),
('Pooja Bhat', 'pooja.b@student.manit.ac.in', 'B.Tech student at MANIT Bhopal, interested in Data Science and SQL.', 'B.Tech 3rd Year', 'ml', 'flexible', 0),
('Varun Teja', 'varun.t@student.nitrkl.ac.in', 'B.Tech student at NIT Rourkela, focused on Mobile Apps with Flutter.', 'B.Tech 2nd Year', 'frontend', 'moderate', 0),
('Aniket Roy', 'aniket.r@student.iiitd.ac.in', 'M.Tech student at IIIT Delhi, specializing in Information Security.', 'M.Tech / Masters', 'backend', 'flexible', 0),
('Ritu Agarwal', 'ritu.a@student.dtu.ac.in', 'B.Tech student at DTU, interested in Cloud Native and AWS.', 'B.Tech 4th Year', 'devops', 'flexible', 0),
('Sameer Khan', 'sameer.k@student.amu.ac.in', 'B.Tech student at AMU, focusing on Web Development and Django.', 'B.Tech 3rd Year', 'backend', 'moderate', 0),
('Nisha Taneja', 'nisha.t@student.igdtuw.ac.in', 'B.Tech student at IGDTUW, interested in Machine Learning and Keras.', 'B.Tech 3rd Year', 'ml', 'flexible', 0),
('Prateek Vats', 'prateek.v@student.pec.ac.in', 'B.Tech student at PEC Chandigarh, focused on Embedded Systems and Arduino.', 'B.Tech 4th Year', 'backend', 'limited', 0),
('Shreya Mishra', 'shreya.m@student.bhu.ac.in', 'M.Tech student at IIT BHU, researching Wireless Sensor Networks.', 'M.Tech / Masters', 'backend', 'moderate', 0),
('Kartik Iyer', 'kartik.i@student.iitj.ac.in', 'B.Tech student at IIT Jodhpur, interested in HCI and AR/VR.', 'B.Tech 2nd Year', 'design', 'flexible', 0),
('Swati Negi', 'swati.n@student.iitr.ac.in', 'PhD scholar at IIT Roorkee, focusing on Hydrology and ML.', 'PhD Scholar', 'ml', 'moderate', 0),
('Abhishek Mani', 'abhishek.m@student.iitgn.ac.in', 'B.Tech student at IIT Gandhinagar, interested in Game Development and Unity.', 'B.Tech 3rd Year', 'frontend', 'flexible', 0),
('Divya Kulkarni', 'divya.k@student.iitp.ac.in', 'B.Tech student at IIT Patna, focusing on Bio-Informatics and Python.', 'B.Tech 4th Year', 'ml', 'moderate', 0),
('Harsh Vardhan', 'harsh.v@student.iitbbs.ac.in', 'B.Tech student at IIT Bhubaneswar, interested in Open Source and Linux Kernel.', 'B.Tech 3rd Year', 'backend', 'flexible', 0),
('Jyoti Kumari', 'jyoti.k@student.nitp.ac.in', 'B.Tech student at NIT Patna, focusing on Android Development with Kotlin.', 'B.Tech 2nd Year', 'frontend', 'flexible', 0),
('Lokesh Choudhary', 'lokesh.c@student.nitrr.ac.in', 'B.Tech student at NIT Raipur, interested in Big Data and Hadoop.', 'B.Tech 4th Year', 'backend', 'limited', 0),
('Manoj Swaminathan', 'manoj.s@student.nitc.ac.in', 'B.Tech student at NIT Calicut, focused on Compiler Design.', 'B.Tech 4th Year', 'backend', 'moderate', 0),
('Nandini Sethi', 'nandini.s@student.nith.ac.in', 'B.Tech student at NIT Hamirpur, interested in Artificial Intelligence and Ethics.', 'B.Tech 3rd Year', 'ml', 'flexible', 0),
('Omkar Gokhale', 'omkar.g@student.vjti.ac.in', 'B.Tech student at VJTI Mumbai, focusing on Finance and Algotrading.', 'B.Tech 4th Year', 'ml', 'moderate', 0),
('Prachi Desai', 'prachi.d@student.coep.ac.in', 'B.Tech student at COEP Pune, interested in VLSI and Digital Systems.', 'B.Tech 3rd Year', 'backend', 'limited', 0),
('Quasar Ali', 'quasar.a@student.jamia.ac.in', 'B.Tech student at Jamia Millia Islamia, focused on Web Architecture.', 'B.Tech 4th Year', 'fullstack', 'flexible', 0),
('Rashmi Rao', 'rashmi.r@student.rvce.edu.in', 'B.E student at RVCE Bangalore, interested in Cloud Computing and Azure.', 'B.Tech 3rd Year', 'devops', 'flexible', 0),
('Sandeep Reddy', 'sandeep.r@student.osmania.ac.in', 'B.Tech student at Osmania University, focusing on Data Mining.', 'B.Tech 4th Year', 'ml', 'moderate', 0),
('Tanmay Shrivastava', 'tanmay.s@student.itbhu.ac.in', 'B.Tech student at IT BHU, interested in Competitive Programming and Algorithms.', 'B.Tech 2nd Year', 'backend', 'flexible', 0),
('Urvashi Rautela', 'urvashi.r@student.uoh.ac.in', 'M.Tech student at University of Hyderabad, specializing in NLP.', 'M.Tech / Masters', 'ml', 'moderate', 0),
('Vinayaka Hegde', 'vinayaka.h@student.bmsce.ac.in', 'B.E student at BMSCE Bangalore, interested in Microcontrollers.', 'B.Tech 3rd Year', 'backend', 'limited', 0),
('Waseem Akram', 'waseem.a@student.manuu.ac.in', 'B.Tech student at MANUU, focused on Localization and I18n.', 'B.Tech 4th Year', 'frontend', 'flexible', 0),
('Xenia Dsilva', 'xenia.d@student.goauniv.ac.in', 'B.Tech student at Goa University, interested in Web3 and Solidity.', 'B.Tech 3rd Year', 'blockchain', 'flexible', 0),
('Yashasvi Jaiswal', 'yashasvi.j@student.hbtu.ac.in', 'B.Tech student at HBTU Kanpur, focusing on Backend with Node.js.', 'B.Tech 2nd Year', 'backend', 'moderate', 0),
('Zainab Bi', 'zainab.b@student.lnct.ac.in', 'B.Tech student at LNCT Bhopal, interested in Java and Spring Boot.', 'B.Tech 4th Year', 'backend', 'flexible', 0),
('Amit Trivedi', 'amit.t@student.svnit.ac.in', 'B.Tech student at SVNIT Surat, focused on Smart Cities and IoT.', 'B.Tech 3rd Year', 'fullstack', 'moderate', 0),
('Bhavyata Shah', 'bhavyata.s@student.daict.ac.in', 'B.Tech student at DA-IICT Gandhinagar, interested in HCI.', 'B.Tech 4th Year', 'design', 'flexible', 0),
('Chirag Lalani', 'chirag.l@student.ldce.ac.in', 'B.Tech student at LD College of Engineering, focusing on PHP and Laravel.', 'B.Tech 4th Year', 'backend', 'flexible', 0);

-- Register some as mentors
INSERT OR IGNORE INTO mentors (user_id, domain, experience_years, max_mentees, bio, is_approved) VALUES
((SELECT id FROM users WHERE email='ramesh.b@iitm.ac.in'), 'Reinforcement Learning', 20, 5, 'Expert in RL and its applications in robotics.', 1),
((SELECT id FROM users WHERE email='sunita.d@iitb.ac.in'), 'Cryptography', 15, 3, 'Teaching crypto and security for over a decade.', 1),
((SELECT id FROM users WHERE email='amitabh.s@iitd.ac.in'), 'Natural Language Processing', 22, 4, 'Researching Indic NLP and language models.', 1),
((SELECT id FROM users WHERE email='kavita.r@iitk.ac.in'), 'Computer Vision', 12, 4, 'Guidance on vision-based research and medical imaging.', 1),
((SELECT id FROM users WHERE email='sanjay.m@iitkgp.ac.in'), 'VLSI & Embedded', 25, 2, 'Industry veteran in systems design.', 1),
((SELECT id FROM users WHERE email='ananya.i@nitk.ac.in'), 'Cloud & IoT', 14, 5, 'Mentoring students in cloud native apps and IoT nodes.', 1);
